repos:

  # Some default pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.1.0
    hooks:

    - id: check-yaml
      name: Check YAML formatting

    - id: mixed-line-ending
      name: Check line endings

    - id: check-merge-conflict
      name: Check merge conflicts

  # Hooks using local packages
  - repo: local
    hooks:

    # Clear output from Jupyter Notebooks
    - id: clear-jupyter-output
      name: Clear output in Jupyter Notebooks
      stages: [commit]
      language: system
      files: \.ipynb$
      entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace

    # Sort imports in scripts
    - id: isort
      name: Sort import statements
      stages: [commit]
      language: system
      entry: python -m isort
      types: [python]
      files: (^notebooks/)

    # Auto-format scripts with black
    - id: black
      name: Format code using black
      stages: [commit]
      language: system
      entry: python -m black
      types: [python]
      files: (^notebooks/)

    # Lint scripts with pylint
    - id: pylint
      name: Check code style using pylint
      language: system
      stages: [commit]
      entry: python -m pylint
      types: [python]
      files: (^notebooks/)
