# Name for the Anaconda environment
name: {{cookiecutter.azure_repo}}

# Project dependencies
dependencies:
  # Python interpreter version
  - python=3.9

  # Add conda dependencies here, examples:
  # - pandas==1.1.0
  # - notebook

  - pip:
    # Add PyPI dependencies here, examples:
    # - pandas==1.1.0
    # - notebook

    # Development dependencies; leave as is!
    - pre-commit
