# Name for the Anaconda environment
name: {{cookiecutter.azure_repo}}

# Project dependencies
dependencies:
  # Python interpreter version
  - python=3.9
  - pip

  # Add conda dependencies here:
  - pandas
  - notebook

  # Development dependencies (leave as is)
  - isort
  - black
  - pylint

  - pip:
    # Add PyPI dependencies here:
{% if cookiecutter.precommit.startswith("y") %}
    # Development dependencies (leave as is)
    - pre-commit
{% endif %}